### Agregaciones

Cuando nos enfrentamos a una gran cantidad de datos, un primer paso es calcular estadísticos mediante agregaciones de los datos, como por ejemplo la media, mediana o la desviación estándar. Con estas medidas podemos resumir el conjunto de los datos.

Numpy tiene una serie de funciones de agregación integradas rápidas para trabajar con sus matrices.

#### Suma

Como primer ejemplo, vamos a calcular la suma de los valores de un array. Lo podemos implementar con la función **built-in** de Python **sum**.

In [1]:
import numpy as np

In [13]:
L = np.random.random(100)
print(L)
print(sum(L))

[0.87394776 0.47089366 0.56534588 0.82311804 0.84788955 0.84677256
 0.72576311 0.94970524 0.66610802 0.40169055 0.35770142 0.02859611
 0.32087094 0.94625438 0.40520605 0.35160478 0.35317388 0.74734771
 0.08987968 0.71374543 0.20178243 0.22801068 0.58632312 0.30380926
 0.03195876 0.63677265 0.75817172 0.90449069 0.97945    0.40863063
 0.53690976 0.37338589 0.56163984 0.74800676 0.16136601 0.21270975
 0.14281567 0.8923603  0.07254907 0.89352288 0.56936234 0.92819731
 0.75385325 0.14236622 0.77677745 0.8947155  0.2715652  0.57109975
 0.67415664 0.8841821  0.7112219  0.14062766 0.57793995 0.7498509
 0.60379635 0.38671075 0.88891214 0.86264618 0.81011024 0.82978891
 0.57801701 0.33086689 0.83055514 0.97455481 0.20217195 0.4797115
 0.10484312 0.2944009  0.78831002 0.81197908 0.3935216  0.81365876
 0.98127223 0.17932169 0.72035109 0.89639668 0.52757801 0.46678581
 0.58379364 0.65724151 0.0237223  0.79460758 0.38860347 0.30047569
 0.89744879 0.11768536 0.11685135 0.52359748 0.78244117 0.397908

In [8]:
np.sum(L)

np.float64(47.52414827660883)

In [10]:
matriz = [[1,2,4],[2,4,5],[1,4,5]]
print(np.sum(matriz))

28


#### Maximo y mínimo

In [14]:
print(min(L),max(L))

0.0237223035441122 0.9812722315750466


Para min,max y sum hay disponible otra sintaxis todavía más corta

In [15]:
print(L.min(),L.max())

0.0237223035441122 0.9812722315750466


### Arregaciones multidimensionales

In [17]:
M = np.random.rand(3,5)
print(M)

[[0.44669516 0.6624789  0.15382566 0.91501846 0.20044198]
 [0.69770805 0.28051617 0.08154826 0.68971935 0.28933749]
 [0.70062101 0.5585236  0.37684447 0.88588752 0.6064878 ]]


Por defecto las funciones de agregacion se aplican sobre todos los elementos de la matriz, sin embargo las funciones de agregacion tienen un parámetro en el que especificamos el eje sobre el cual queremos aplicar dicha operacion.

In [19]:
M.min(axis=0)
M.min(axis=1)

array([0.15382566, 0.08154826, 0.37684447])

### Argumento que maximiza o minimiza (argmax,argmin)

Para terminar, veamos dos funciones de localizacion. Una que nos permite obtener el indice del elemento maximo y otra que nos permite obtener
el indice del valor minimo

In [20]:
salida_neuronas = np.random.rand (7)
etiquetas_neurona = ["Azul","Verde","Rojo","Negro","Blanco","Violeta","Naranja"]

In [24]:
for salida, color in zip(salida_neuronas,etiquetas_neurona):
    print(color,"prob:",salida)

#Dada la salida de las neuronas, ¿cual es el color preferido del cliente?

indice_neurona_preferida = np.argmax(salida_neuronas)
print("El color escogido va a ser",etiquetas_neurona[indice_neurona_preferida])
#Y el color que menos cree que le gusta
indice_neurona_minima = np.argmin(salida_neuronas)
print("El color que menos debes ofrecer es",etiquetas_neurona[indice_neurona_minima])


Azul prob: 0.08244605630411284
Verde prob: 0.41771155252307135
Rojo prob: 0.6127633382012564
Negro prob: 0.11934580674860484
Blanco prob: 0.7471602317017776
Violeta prob: 0.9656987795363474
Naranja prob: 0.2723551289670456
El color escogido va a ser Violeta
El color que menos debes ofrecer es Azul
