In [1]:
import numpy as np

Vector es una array con solo una dimension

In [6]:
array_vec = np.array([1,2,3,4,5])
print(arra_vec)

[1 2 3 4 5]


In [ ]:
el acceso es igual que en las listas

In [9]:
print(array_vec[0])
print(array_vec[-1])
print(array_vec[-2])

1
5
4


Ojo, que ya no son listas, aunque lo parecen ya no lo son. Incluso los tipos de datos no son los que conocemos sino que numpy aporta nuevos tipos de datos

In [15]:
print(type(array_vec))
print(type(array_vec[0]))
print(array_vec.dtype)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64


### Matrices

Creemos ahora un array multidimensional

In [17]:
array_multi = np.array([[1,2,3],[3,4,5],[7,8,9]])
print(array_multi)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


Otra ventaja de numpy es que nos imprime las matrices en una forma que nos permite mejor visualizarlas.

Matrices con valores: Hay diferentes maneras de crear arrays, pero en ocasiones necesitamos tener definidas las matrices con un unico valor.

In [20]:
## Matriz identidad
I =  np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
## Matriz de 0s
matriz_zeros =  np.zeros((3,2))
print(matriz_zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
## Matriz de 1s
matriz_ones =  np.ones((3,2))
print(matriz_ones)
print(matriz_ones.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64


In [26]:
## Matriz de 100s
matriz_hundreds =  np.full((3,2),100)
print(matriz_hundreds)

[[100 100]
 [100 100]
 [100 100]]


## Creacion de secuencias

¿Recuerdas range()? Lo usábamos en listas para crear secuencias, estableciendo el punto de inicio, de parada, y el salto entre elementos. En numpy hay algo parecido denominado arange. Te dejo el enlace a la documentación.

In [34]:
lista = list(range(0,100,2))
# print(lista)

## Array del 0 al 9
array_0_9= np.arange(9)
print(array_0_9)
## Del 0 al 9 con saltos de 2
array_0_9_2 = np.arange(0,10,2)
print(array_0_9_2)
## Del 0 al 10 con saltos de 0.5
array_0_9_00 = np.arange(0,10,0.5)
print(array_0_9_00)
## Especificando el tipo de dato

array = np.arange(0,10,2,np.float64)
print(array)
print(array.dtype)



[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0. 2. 4. 6. 8.]
float64


### Random

Otra opción es usar el paquete random de numpy. Muy útil cuando tenemos que crear secuencias aleatorias, y lo mejor de todo es que tiene una gran cantidad de opciones para configurar. Consulta la documentación para más detalle.

In [42]:
print(np.random.rand(5))

[0.73982938 0.91412826 0.98715163 0.56786876 0.59809141]


In [43]:
matriz_aleatoria = np.random.rand(3,4)
print(matriz_aleatoria)

[[0.84829975 0.85787872 0.51614059 0.48546625]
 [0.86266891 0.75662774 0.07690114 0.38976804]
 [0.50311192 0.98216826 0.61511568 0.54893022]]


In [46]:
matriz_int = np.random.randint(3,12, size=(3,4))
print(matriz_int)

[[10 11 10  7]
 [ 6 10 10  9]
 [ 5 10  6  6]]


In [49]:
### Unidimensional 
matriz_int = np.random.randint(3,12, size=5)
print(matriz_int)

[8 4 7 4 8]


### Seed

Como habrás podido comprobar, cada ejecución de una secuencia aleatoria es diferente.

Fijando una semilla, todas las secuencias aleatorias que ejecutes (si tienen los mismos argumentos), tendrán siempre el mismo output. Se usa mucho cuando queremos replicar resultados, o compartirlos con otros compañeros. Los resultados que obtengas en este Notebook no serán los mismos que obtenga el compañero, en caso de haber un factor aleatorio, por lo que no vamos a poder comparar los Notebooks... A no ser que ambos fijéis la misma semilla.

In [55]:
np.random.seed(1234)
print(np.random.rand(10))



[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]


In [57]:
np.random.seed(5678)
print(np.random.rand(10))

[0.48932698 0.05933244 0.36620243 0.51886544 0.59822501 0.43061449
 0.17863405 0.2852539  0.07143863 0.18471334]


In [58]:
np.random.seed(1234)
print(np.random.rand(10))


[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]


## Atributos

Atributos y dimensiones
Hay ciertos atributos de los arrays que debemos conocer. Estos atributos son:

* ndim: es el número de dimensiones. Número de niveles que tiene el array de numpy.

* shape: tamaño de cada una de las dimensiones. Devuelve el resultado en formato tupla.

* size: cantidad de elementos del array.

* dtype: nos dice el tipo (numpy) de los elementos que contiene un array.

### Numpy: Indexado y Slicing

Como accedemos a los elementos de un Array?

In [13]:
import numpy as np
array_1= np.array([1,2,3,4,5])
array_2= np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3 = np.array([[[1, 10], [2, 20], [3, 30]],
                    [[4, 40], [5, 50], [6, 60]],
                    [[7, 70], [8, 80], [9, 90]]])
print(array_1.ndim)
print(array_2.ndim)
print(array_3.ndim)

1
2
3


In [4]:
print(array_1[0])
print(array_1[2:5])


1
[3 4 5]


 Con dos dimensiones:

In [5]:
###Primera fila

print(array_2[0])

[1 2 3]


In [7]:
###Segundo elemento de la primera fila

print(array_2[0][1])
print(array_2[0,1])

2
2


In [12]:
###Tipo del primer elemento
print(type(array_2[0,0]))
print(type(array_2[0][0]))
print(type(array_2[0]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.ndarray'>


In [14]:
### Ahora con el Array 3

print(array_3)

[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]


In [18]:
#Primera matriz
print(array_3[0])

[[ 1 10]
 [ 2 20]
 [ 3 30]]


In [20]:
#Ultimo elemento de la última fila de cada matriz

print(array_3[-1][-1][-1])
print(array_3[-1-1-1])

90
[[ 1 10]
 [ 2 20]
 [ 3 30]]


### Slicing y Subarrays

 Ya hemos visto que podemos acceder a los elementos individuales del array usando la sintaxis con corchetes,pero si necesitamos acceder a un conjunto de valores, tendremos que usar :.
* El slicing (por dimensión del array) sigue la siguiente sintaxis:

* x[start:stop:step]

Por defecto, si no ponemos alguno de estos argumentos, start = 0, stop = tamaño de la dimensión y step = 1.
Recuerda, al igual que en listas, el start está incluido, mientras que el stop no.

In [31]:
### Array de 10 elementos

x = np.arange(10)
print (x)

print("Del primer elemento al quinto", x[0:5:])
print("Del primer elemento al quinto, con salto de 2", x[0:5:2])
print("Desde el quinto, hacia adelante", x[5::])
print("Desde el quinto, hacia adelante", x[5:])#equivalente
print("Desde el quinto, hasta el penúltimo", x[5:-1])
print("Desde el quinto, hasta el primero", x[5:1:-1])
print("Sacar una copia",x[:])
print("Sacar una copia",x.copy()) ##Equivalente
print("Ultimos dos elementos",x[-2:]) ##Equivalente


[0 1 2 3 4 5 6 7 8 9]
Del primer elemento al quinto [0 1 2 3 4]
Del primer elemento al quinto, con salto de 2 [0 2 4]
Desde el quinto, hacia adelante [5 6 7 8 9]
Desde el quinto, hacia adelante [5 6 7 8 9]
Desde el quinto, hasta el penúltimo [5 6 7 8]
Desde el quinto, hasta el primero [5 4 3 2]
Sacar una copia [0 1 2 3 4 5 6 7 8 9]
Sacar una copia [0 1 2 3 4 5 6 7 8 9]
Ultimos dos elementos [8 9]


Veamos ahora algunos ejemplos de slicing con arrays multidimensionales

In [32]:
import numpy as np

array_multi = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(array_multi)

print("2 primeras filas y 3 primeras columnas\n", array_multi[:2, :3])

print("Todas las filas, cada dos columnas\n", array_multi[:, ::2])

print("Invertir las filas\n", array_multi[::-1, :])

print("Invertir columnas\n", array_multi[:, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2 primeras filas y 3 primeras columnas
 [[1 2 3]
 [6 7 8]]
Todas las filas, cada dos columnas
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
Invertir las filas
 [[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Invertir columnas
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


Otra forma de quedarnos con los sub arrays, o de filtrarlos es mediante una mascara de booleanos.
La máscara tiene las mismas dimensiones que el array, y donde haya un True, se quedará con ese valor, pero en donde haya un
False lo ignorará

In [34]:
x = np.array([2,4,5,2,3,7,2])

In [35]:
#Mostrar aquellos valores que sean 2

print(x)
print(x==2)

[2 4 5 2 3 7 2]
[ True False False  True False False  True]


In [36]:
x_bools =np.array(x==2)
print(x_bools)
sub_x=x[x_bools]
print(sub_x)
                  

[ True False False  True False False  True]
[2 2 2]


### Reshape

Con el Reshape podremos cambiar las dimensiones de los Arrays, siempre y cuando en numero de elementos sea posible. Por ejemplo
si tenemos 4 elementos, no podremos hacer una matriz de 3x3.

Este metodo se puede utilizar en infinidad de casos, pero lo más habitual sería, partiendo de un array de una dimensión, convirtiéndolo en
una multidimensión.


In [39]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [43]:
y=x.reshape(3,3)
print(y)
print(y.ndim)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [49]:
x = np.arange(30)
x1= x.reshape(2,5,3)
y1= x.reshape(6,5)
print(x1)
print(y1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
