## Concatenado y sustitución

Concatenado

Para concatenar matrices, numpy tiene varios métodos: **np.concatenate**, **np.vstack** o **np.hstack**. 
Lo único que hay que tener en cuenta es que coincidan las dimensiones, para que el concatenado sea correcto.

In [1]:
import numpy as np

x = [1, 2, 3]
y = [3, 2, 1]
x + y

[1, 2, 3, 3, 2, 1]

In [4]:
x_np= np.array(x)
y_np= np.array(y)

#Si usamos el signo + lo que hará será sumar los valores dentro de los arrays y no los concatenará#

np.concatenate([x_np,y_np])

array([1, 2, 3, 3, 2, 1])

In [6]:
z_np= np.array([99,99,99])
np.concatenate([x_np,y_np,z_np])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [7]:
## Ahora con arrays bidimensionales

xy = np.array ([[1,2,3],
               [4,5,6]])

np.concatenate([xy,xy])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Ahora podemos jugar con los ejes a traves del argumento axis

In [8]:
np.concatenate ([xy,xy],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Si tenemos arrays con varias dimensiones:

In [11]:
xy = np.array([[1, 2, 3], [4, 5, 6], [101, 11, 12]])
x = np.array([7, 8, 9])

##Para concatenar arrays con diferentes dimensiones

np.vstack([xy,x])

array([[  1,   2,   3],
       [  4,   5,   6],
       [101,  11,  12],
       [  7,   8,   9]])

In [12]:

xy = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([[7], [8]])

# Concatenado horizontal
resultado = np.hstack((xy, x))

print(resultado)

[[1 2 3 7]
 [4 5 6 8]]


In [13]:
np.concatenate([xy,x],axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

### Sustitución

En numpy podemos utilizar la funcion where para hacer sustituciones de valores que cuplan o no una condicion.


In [20]:
xy = np.array([[1, 2, 3], 
               [4, 5, 6]])

##Sustituir valores pares por ceros e impares por unos

np.where(xy % 2 ==0,0,1)

##Sustituir valores menores que 4 por 10 y el resto dejar todo igual.

np.where (xy<4,10,xy)

array([[10, 10, 10],
       [ 4,  5,  6]])

In [28]:
texto = np.array(["la", "casa", "es", "una", "casa", "roja"])

# Sustituir "casa" por "cueva"
np.where(texto == "casa", "cueva",texto)

array(['la', 'cueva', 'es', 'una', 'cueva', 'roja'], dtype='<U5')

## Splitting

Al igual que hacíamos el concatenado, podemos realizar la operación contraria mediante np.split, np.hsplit y np.vsplit.

Le podemos pasar una lista de índices por los que realizar el Split

In [8]:
import numpy as np

In [9]:
x= np.array ([1,2,3,99,99,3,2,1])
print (x)

[ 1  2  3 99 99  3  2  1]


In [14]:
##Split en 3 partes por el elemento 3 y el elemento 5

#Elemento 3

x1,x2 = np.split(x,[2])
print(x1,x2)

x1,x2,x3 = np.split(x,[2,5])
print(x1,x2,x3)


[1 2] [ 3 99 99  3  2  1]
[1 2] [ 3 99 99] [3 2 1]


In [15]:
print(x[:2])
print(x[2:5])
print(x[5:])


[1 2]
[ 3 99 99]
[3 2 1]


N puntos de splitting, supone crear N+1 Subarrays nuevos

np.hsplit y np.vsplit funcionan de manera similar

In [19]:
grid = np.arange(16).reshape((4,4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
###Split vertical por la fila 2 (es decir separar el array por la mitad de las filas)

upper,lower= np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [23]:
#Split horizontal por la columna 3 (es decir separar la ultima columna del resto)
left,right = np.hsplit(grid,[3])
print (left)
print (right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


### Vistas y copias

# Vistas

Una característica importante y extremadamente útil en los arrays es que cuando **hacemos**  
**slicing**, **realmente obtenemos de los arrays vistas**, **no copias**. ¿Esto qué significa? Que si  
hacemos *slicing*, creando un nuevo array, y lo modificamos, también estaremos modificando  
el original.

Esto difiere con las listas de Python, que al aplicar *slicing* lo que obtenemos es una copia, y  
por tanto cualquier modificación sobre la nueva lista no afectará a la lista original.

Declaro un array

In [25]:
x2 = np.ones((3,4))
x2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Extraemos una matriz 2x2

In [26]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[1. 1.]
 [1. 1.]]


In [28]:
x2_sub[0,0] = 35
print(x2_sub)

[[35.  1.]
 [ 1.  1.]]


In [29]:
print(x2)

[[35.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


Esta característica es bastante util ya que si trabajamos con datasets muy grandes, podremos acceder y procesar partes del dataset original, sin necesidad de hacer copias, y por tanto, sin sobrecargar la memoria. 

### Copias

Siempre tenemos la opcion de realizar copias del array mediante la sentencia copy()

In [32]:
x2_sub_copy = x2[:2,:2].copy()
print (x2_sub_copy)

[[35.  1.]
 [ 1.  1.]]


Ahora si modificamos el subarray, el original se quedará como estaba

In [34]:
x2_sub_copy[1,1] = 123
print(x2_sub_copy)

[[ 35.   1.]
 [  1. 123.]]


In [35]:
print(x2)

[[35.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
