## Ejercicio 1

Rafa, Nacho y Clara quieren comprar palmeras, donuts, hojaldres y tartas. Cada uno necesita diferentes cantidades y pueden elegir dos tiendas: Manolo Bakes y Starbucks.

Las siguiente tablas muestran, respectivamente, la cantidad que cada uno necesita, y los precios en cada una de las tiendas

|        | Palmeras | Donuts | Hojaldres | Tartas |
|--------|----------|--------|-----------|--------|
| Rafa   | 6        | 5      | 3         | 1      |
| Nacho  | 3        | 6      | 2         | 2      |
| Clara  | 3        | 4      | 3         | 1      |

|          | Manolo Bakes | Starbucks |
|----------|--------------|-----------|
| Palmera  | 1.50         | 1.00      |
| Donut    | 2.00         | 2.50      |
| Hojaldre | 5.00         | 4.50      |
| Tarta    | 16.00        | 17.00     |



Por ejemplo, si Rafa compra en Manolo Bakes gastaría:


y si compra en Starbucks gastaría:


SE PIDE: Genera la matriz que exprese la cantidad que cada persona gastaría en cada tienda, y recomienda a cada uno dónde debería hacer sus compras (pista: donde le cueste menos, ¿no?)

REQUISITIO: Emplea Numpy, su tipo array y sus operaciones para la resolución del ejercicio.

In [13]:
import numpy as np

# Matriz de cantidades
cantidades = np.array([
    [6, 5, 3, 1],  # Rafa
    [3, 6, 2, 2],  # Nacho
    [3, 4, 3, 1]   # Clara
])

# Matriz de precios en Manolo Bakes
precios_manolo = np.array([1.50, 2.00, 5.00, 16.00])

# Matriz de precios en Starbucks
precios_starbucks = np.array([1.00, 2.50, 4.50, 17.00])

# Calcular el costo total en cada tienda
costos_manolo = np.dot(cantidades, precios_manolo)
costos_starbucks = np.dot(cantidades, precios_starbucks)

# Crear la matriz de costos
costos = np.array([costos_manolo, costos_starbucks]).T

# Recomendar la tienda más económica
recomendaciones = np.where(costos_manolo < costos_starbucks, 'Manolo Bakes', 'Starbucks')

# Resultados
print("Matriz de costos:")
print(costos)
print("\nRecomendaciones:")
for i, persona in enumerate(['Rafa', 'Nacho', 'Clara']):
    print(f"{persona} debería comprar en {recomendaciones[i]}")

Matriz de costos:
[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]

Recomendaciones:
Rafa debería comprar en Starbucks
Nacho debería comprar en Manolo Bakes
Clara debería comprar en Starbucks


## Ejercicio 2

PARTE II: Clasificador de Películas
II.1: Similitud entre películas

Vamos a calcular similitudes entre películas. Para ello las clasificasmos según generos, en concreto tenemos:

Toy Story: Aventura, Animación, Comedia
Jumanji: Aventura
Mortal Kombat: Acción, Aventura
Pocahontas: Animación, Romance
Y ahora calcularemos su similitud por el método del coseno. Para ello:

Convierte cada película en un vector y almacenalo en un diccionario con clave el nombre de la película. Pista: Para convertirlo en vector, crea un vector/lista por película con esta estructura (¿qué valores puedes darle por género?):

In [2]:
peliculas = { "Toy Story":[0,1,1,1,0],
             "Jumanji":[0,1,0,0,0],
             "Mortal Kombat":[1,1,0,0,0],
             "Pocahontas":[0,0,1,0,1]}
             

In [3]:
list(peliculas.values())

[[0, 1, 1, 1, 0], [0, 1, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 1]]

In [14]:
vectores=list(peliculas.values())
matriz_peliculas_np = np.array(vectores)
print(matriz_peliculas_np)

[[0 1 1 1 0]
 [0 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 0 1]]


In [15]:
for pelicula1, vector in peliculas.items():
    coseno_maximo = -1
    pelicula_similar = None
    
    for pelicula2, vector2 in peliculas.items():
        if pelicula1 != pelicula2:
            coseno = np.dot(vector, vector2) / (np.linalg.norm(vector) * np.linalg.norm(vector2))
            if coseno > coseno_maximo:
                pelicula_similar = pelicula2
                coseno_maximo = coseno
    
    print(f"Para {pelicula1} la más parecida es {pelicula_similar}, grado de confianza: {coseno_maximo}")

Para Toy Story la más parecida es Jumanji, grado de confianza: 0.5773502691896258
Para Jumanji la más parecida es Mortal Kombat, grado de confianza: 0.7071067811865475
Para Mortal Kombat la más parecida es Jumanji, grado de confianza: 0.7071067811865475
Para Pocahontas la más parecida es Toy Story, grado de confianza: 0.40824829046386296
