### Ejercicio 1

Concatena los siguientes arrays verticalmente

In [5]:
import numpy as np

a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

In [6]:
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Ejercicio 2

Concatena los siguientes arrays horizontamente

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a_b = np.hstack((a, b))
(a_b)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Ejercicio 3

Crea un array unidimensional que vaya del 0 al 9. Llámalo my_array.

Multiplica cada uno de los elementos de my_array por 10, en un nuevo array
Accede al primer elemento del array
Accede al último elemento del array
Imprime por pantalla los numeros del 1 al 7

In [27]:
my_array = np.arange(10)

my_array_multiplied = my_array * 10

primer_elemento = my_array[0]

ultimo_elemento = my_array[-1]

print(my_array[1:8])

print("Array original:", my_array)
print("Array multiplicado por 10:", my_array_multiplied)
print("Primer elemento:", primer_elemento)
print("Último elemento:", ultimo_elemento)

[1 2 3 4 5 6 7]
Array original: [0 1 2 3 4 5 6 7 8 9]
Array multiplicado por 10: [ 0 10 20 30 40 50 60 70 80 90]
Primer elemento: 0
Último elemento: 9


### Ejercicio 4

Obtén la siguiente secuencia:

[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [26]:
secuencia = np.arange(1, 50, 3)

print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


### Ejercicio 5

Obtén la siguiente secuencia

[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]

In [16]:
secuencia = np.arange(4, 1, -0.25)

print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


### Ejercicio 6

Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [17]:
secuencia_aleatoria = np.random.rand(4, 5, 3)

print(secuencia_aleatoria)

[[[0.07797143 0.05726598 0.92456466]
  [0.00844921 0.8770562  0.89464859]
  [0.22845864 0.55651876 0.64160538]
  [0.20556883 0.62800471 0.18001229]
  [0.50752766 0.43780211 0.59223421]]

 [[0.61790559 0.28359188 0.55903446]
  [0.79265777 0.20916919 0.64426311]
  [0.64780046 0.13129325 0.88139524]
  [0.53666205 0.83589638 0.27367592]
  [0.48274126 0.62317305 0.55476532]]

 [[0.89915036 0.79062465 0.93205101]
  [0.96729985 0.81615367 0.96555701]
  [0.30347498 0.24952053 0.97942764]
  [0.8746432  0.01377368 0.6541047 ]
  [0.91958352 0.03676865 0.8232772 ]]

 [[0.46150909 0.64700863 0.39243043]
  [0.60908926 0.9955294  0.55452128]
  [0.72218459 0.98014837 0.28154295]
  [0.71774742 0.96602418 0.52800193]
  [0.31823794 0.13554908 0.36897695]]]


### Ejercicio 7

Crea una secuencia de números que vayan del 0 al 10.
Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [25]:
secuencia = np.arange(11)

array_sustituido = secuencia.copy()
array_sustituido[3:9] = -1

array_negado = secuencia.copy()
array_negado[3:9] = -array_negado[3:9]

print("Secuencia original:", secuencia)
print("Array con elementos sustituidos:", array_sustituido)
print("Array con elementos negados:", array_negado)

Secuencia original: [ 0  1  2  3  4  5  6  7  8  9 10]
Array con elementos sustituidos: [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Array con elementos negados: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


### Ejercicio 8

Crea una matriz de 6x6, con una secuencia del 1 al 36
Obten una vista de su nucleo interior de 2x2 (es decir la submatriz que contiene los valores 15,16,21,22)
Modifica la matriz inicial (la del apartado 1.) de dos formas diferentes de manera que los 4 elementos centrales valgan el doble de su valor

In [20]:

matriz = np.arange(1, 37).reshape(6, 6)

vista_interior = matriz[2:4, 2:4]

matriz_modificada1 = matriz.copy()
matriz_modificada1[2:4, 2:4] *= 2

matriz_modificada2 = matriz.copy()
matriz_modificada2[2:4, 2:4] = matriz_modificada2[2:4, 2:4] * 2

print("Matriz original:")
print(matriz)
print("\nVista del núcleo interior 2x2:")
print(vista_interior)
print("\nMatriz modificada (primera forma):")
print(matriz_modificada1)
print("\nMatriz modificada (segunda forma):")
print(matriz_modificada2)

Matriz original:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Vista del núcleo interior 2x2:
[[15 16]
 [21 22]]

Matriz modificada (primera forma):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 30 32 17 18]
 [19 20 42 44 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Matriz modificada (segunda forma):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 30 32 17 18]
 [19 20 42 44 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


### Ejercicio 9

En un array aleatorio de números enteros entre 1 y 11, de shape (2,3,2), sustituye todos los impares de my_array por -1. Usa where



In [24]:
import numpy as np

my_array = np.random.randint(1, 12, size=(2, 3, 2))

my_array_modificado = np.where(my_array % 2 != 0, -1, my_array)

print("Array original:")
print(my_array)
print("\nArray modificado (impares sustituidos por -1):")
print(my_array_modificado)

Array original:
[[[ 2  1]
  [10  8]
  [ 1  3]]

 [[ 4  1]
  [ 9  2]
  [ 8  8]]]

Array modificado (impares sustituidos por -1):
[[[ 2 -1]
  [10  8]
  [-1 -1]]

 [[ 4 -1]
  [-1  2]
  [ 8  8]]]


### Ejercicio 10

Encuentra los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. Usa np.where

In [23]:
import numpy as np

vector = np.array([1, 2, 0, 0, 4, 0])

indices_no_cero = np.where(vector != 0)[0]

valores_no_cero = vector[indices_no_cero]

print("Vector original:", vector)
print("Índices de valores no cero:", indices_no_cero)
print("Valores no cero:", valores_no_cero)

Vector original: [1 2 0 0 4 0]
Índices de valores no cero: [0 1 4]
Valores no cero: [1 2 4]
