### Ejercicio 1

Importa el módulo de numpy y obtén su versión.

In [3]:
import numpy as np
print(np.__version__)

2.2.1


### Ejercicio 2

Crea un array de una dimensión que vaya de 0 a 9. Llamalo my_array

In [6]:
my_array =  np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


### Ejercicio 3

Crea un array 3x3, que sea todo a True

In [9]:
matriz_hundreds =  np.full((3,3),True)
print(matriz_hundreds)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Ejercicio 4

Extrae todos los impares de my_array

In [18]:
valores_impares = np.array(my_array%2!=0)
print(valores_impares)
sub_x_impares= my_array[valores_impares]
print(sub_x_impares)

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


### Ejercicio 5

En un nuevo array, sustituye todos los impares de my_array por -1

In [24]:
my_array[my_array % 2 != 0] = -1
print (my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Ejercicio 6

Convierte my_array en un nuevo array de dos dimensiones mediante reshape.

In [31]:
my_array_resize=my_array.reshape(2,5)
print(my_array_resize)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


### Ejercicio 7

Crea una matriz de 4x5, con una secuencia del 1 al 20
Invierte totalmente la matriz. Tanto las filas, como las columnas

In [39]:
my_matriz = np.arange(1,21)
print(my_matriz)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [40]:
my_matriz_reshape = my_matriz.reshape(4,5)
print(my_matriz_reshape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
my_matriz_invertida = (my_matriz_reshape[::-1, :])
print(my_matriz_invertida)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [45]:
my_matriz_invertida_2 = (my_matriz_invertida[:, ::-1]) 
print(my_matriz_invertida_2)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


### Ejercicio 8

In [52]:
print(my_matriz_invertida_2[-2:, -2:])

[[7 6]
 [2 1]]


### Ejercicio 9

In [54]:
# Acceder a los valores específicos
valores_especificos = np.array([[my_matriz_invertida_2[3, 4], my_matriz_invertida_2[3, 2], my_matriz_invertida_2[3, 0]],
                                [my_matriz_invertida_2[1, 4], my_matriz_invertida_2[1, 2], my_matriz_invertida_2[1, 0]]])

print(valores_especificos)

[[ 1  3  5]
 [11 13 15]]


### Ejercicio 10

In [58]:
x = np.random.randint(10, 20, size=(5, 2, 6))

num_elementos = x.size

num_dimensiones = x.ndim

shape = x.shape
print (x)
print("1. Número de elementos:", num_elementos)
print("2. Número de dimensiones:", num_dimensiones)
print("3. Elementos por dimensión (shape):", shape)

[[[11 19 12 14 17 19]
  [12 14 10 14 11 12]]

 [[19 11 15 18 14 17]
  [11 12 10 13 13 16]]

 [[12 16 19 13 14 14]
  [19 17 11 10 19 10]]

 [[14 13 11 12 16 15]
  [16 14 17 11 16 19]]

 [[19 14 19 13 19 13]
  [14 14 17 19 18 17]]]
1. Número de elementos: 60
2. Número de dimensiones: 3
3. Elementos por dimensión (shape): (5, 2, 6)


### Ejercicio 11

In [61]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

my_x = np.array(x=="Loro")
sub_x= x[my_x]
print(sub_x)


['Loro' 'Loro']
