### PART I: Nuevos alumnos, "nuevo" algoritmo

Apartado 1. Como en la práctica obligatoria de la unidad anterior, se han incorporado dos alumnos a la clase de Dena Aidon: Teresa y Udo. Ambos han rellenado el cuestionario de comer y volar, de la siguiente forma:

Teresa: Comer: -2, Volar: -5
Udo: Comer: 0, Volar: 4

1.1 A partir de la clase de Dena Aidon, dada como una lista de listas o vectores fila, crea un array de Numpy.
1.2 Añade a Teresa y Udo de dos formas diferentes mediante concatenaciones

In [1]:
import numpy as np

In [2]:
alumnos_aidone = [[5, 4],
                  [2, -3],
                  [3, 5],
                  [-5, 4],
                  [0, -1],
                  [3, 2],
                  [-1, 1],
                  [5, -2],
                  [-5, 3],
                  [-5, 1]]

array_alumnos = np.array(alumnos_aidone)

In [3]:
teresa = np.array([-2, -5])
udo = np.array([0, 4])

In [4]:
array_alumnos_vstack = np.vstack((array_alumnos, teresa, udo))
array_alumnos_append = np.append(array_alumnos, [teresa, udo], axis=0)
print("Array original de alumnos:")
print(array_alumnos)
print("\nArray con Teresa y Udo añadidos usando np.vstack:")
print(array_alumnos_vstack)
print("\nArray con Teresa y Udo añadidos usando np.append:")
print(array_alumnos_append)

Array original de alumnos:
[[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]]

Array con Teresa y Udo añadidos usando np.vstack:
[[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]
 [-2 -5]
 [ 0  4]]

Array con Teresa y Udo añadidos usando np.append:
[[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]
 [-2 -5]
 [ 0  4]]


**Apartado 2**. Modificar el algoritmo de elección de la clase extraescolar principal (el presentado en la siguiente celda) de forma que:

2.1 En vez de emplear el diccionario de reparto empleemos una matriz de (12x3) incializada con 0 en todas sus posiciones.

2.2 Emplee alguna de las funciones de la librería numpy en las líneas señaladas para hacer los cálculos

2.3 Utilice alguna de las funciones de agregación vistas para obtener la clase extraescolar asignada

In [7]:
alumnos_ref = ["Rodrigo", "Gabriela", "Mateo"]
lista_alumnos = ['Rodrigo', 'Lucia', 'Alejandro', 'Valeria', 'Javier', 'Camila', 'Diego', 'Gabriela', 'Mateo', 'Sofía', 'Teresa', 'Udo']
curso_asignado = ["CAI", "ER", "NMPC"]

matriz_reparto = np.zeros((12, 3), dtype=int)

alumnos_aidone = np.array([[5, 4],
                           [2, -3],
                           [3, 5],
                           [-5, 4],
                           [0, -1],
                           [3, 2],
                           [-1, 1],
                           [5, -2],
                           [-5, 3],
                           [-5, 1],
                           [-2, -5],
                           [0, 4]])

num_alumnos = len(lista_alumnos)

for i_vector in range(num_alumnos):
    alumno = lista_alumnos[i_vector]
    vector_alumno = alumnos_aidone[i_vector]
    print(f"Par {alumno} con vector {vector_alumno}:")

    vector_distancias = np.full(3, 1000) 

    for indice_curso, alumno_ref in enumerate(alumnos_ref):
        indice_alumno_ref = lista_alumnos.index(alumno_ref)
        vec_ref = alumnos_aidone[indice_alumno_ref]

        distancia = np.linalg.norm(vector_alumno - vec_ref) 
        vector_distancias[indice_curso] = distancia

    indice_curso_elegido = np.argmin(vector_distancias) 
    print(f"{curso_asignado[indice_curso_elegido]}")
    matriz_reparto[i_vector, indice_curso_elegido] = 1 

print("\nMatriz de reparto:")
print(matriz_reparto)

Par Rodrigo con vector [5 4]:
CAI
Par Lucia con vector [ 2 -3]:
ER
Par Alejandro con vector [3 5]:
CAI
Par Valeria con vector [-5  4]:
NMPC
Par Javier con vector [ 0 -1]:
ER
Par Camila con vector [3 2]:
CAI
Par Diego con vector [-1  1]:
NMPC
Par Gabriela con vector [ 5 -2]:
ER
Par Mateo con vector [-5  3]:
NMPC
Par Sofía con vector [-5  1]:
NMPC
Par Teresa con vector [-2 -5]:
ER
Par Udo con vector [0 4]:
CAI

Matriz de reparto:
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


Apartado 2.3
¿A qué clases asignaremos a Teresa y a Udo?

+ Teresa: Asignada al curso ER.

+ Udo: Asignado al curso CAI.

### PART II:Mini hundir la flota

Crea un tablero de 10x10 relleno del carácter espacio " ". 

* (Utiliza un array de Numpy para representarlo y creálo utilizando las inicializaciones que hemos aprendidio)
* Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
* Recibe un disparo en uno de los barcos, sustituyendo la O por una X
* Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
* Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.