## Vectores con Numpy

In [2]:
import numpy as np
np.__version__

'2.2.1'

In [5]:
vector_np = np.array([2,3])
vector_lista = [2,3]

In [8]:
print(type(vector_np))

<class 'numpy.ndarray'>


In [9]:
vector_1 = np.array([23,-4,5])
vec_2 = [12,3,-12]
vector_2 =  np.array(vec_2)

In [11]:
### Sumas:

vec_suma= vector_1+vector_2
print(vec_suma)

[35 -1 -7]


In [13]:
### Restas
vec_resta = vector_1-vector_2
print(vec_resta)

[11 -7 17]


In [14]:
### Producto por un escalar
vec_escalar = 3*vector_1
print(vec_escalar)

[ 69 -12  15]


In [16]:
### Producto por un escalar

dot_product = np.dot(vector_1,vector_2)
print(dot_product)


204


In [20]:
###Norma, longitud o magnitud

norm_1 = np.linalg.norm(vector_1)
norm_2 = np.linalg.norm(vector_2)

print(round(norm_1))
print(round(norm_2))


24
17


In [22]:
### Coseno del ángulo

cose_ang_1_2 = dot_product/(norm_1*norm_2)
print(cose_ang_1_2)

0.49580912449444803


In [24]:
### Distancia entre vectores
dist_v1_v2 = np.linalg.norm(vector_1-vector_2)
print(dist_v1_v2)

21.42428528562855


In [25]:
### Ejemplo1 1:

alumnos_aldone = {
    "Roberto": [5, 4],
    "Lucia": [2, -3],
    "Alejandro": [3, 5],
    "Valeria": [-5, 4],
    "Javier": [0, -1],
    "Camila": [3, 2],
    "Diego": [-1, 1],
    "Gabriela": [5, -2],
    "Mateo": [-5, 3],
    "Sofia": [-5, 1]
}

In [27]:
alumnos_np ={}
for alumno,vec_list in alumnos_aldone.items():
    alumnos_np[alumno]=np.array(vec_list)
print(alumnos_np)

{'Roberto': array([5, 4]), 'Lucia': array([ 2, -3]), 'Alejandro': array([3, 5]), 'Valeria': array([-5,  4]), 'Javier': array([ 0, -1]), 'Camila': array([3, 2]), 'Diego': array([-1,  1]), 'Gabriela': array([ 5, -2]), 'Mateo': array([-5,  3]), 'Sofia': array([-5,  1])}


## Matrices en Numpy

In [34]:
matriz = [[1,2,4],
          [3,5,6]]
matriz_np = np.array(matriz)


A= np.array([[1,3,2],
             [1,0,0],
            [1,2,2]])
B= np.array([[1,0,5],
             [7,5,0],
            [2,1,1]])

print(matriz)
print(matriz_np)
print(A)
print(B)

[[1, 2, 4], [3, 5, 6]]
[[1 2 4]
 [3 5 6]]
[[1 3 2]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [35]:
### Producto por un escalar
producto = 3*A
print("3*A:\n", producto)
### Suma

3*A:
 [[3 9 6]
 [3 0 0]
 [3 6 6]]


In [36]:
###Suma

suma = A+B
print("Suma, A+B:\n", suma)

Suma, A+B:
 [[2 3 7]
 [8 5 0]
 [3 3 3]]


In [40]:
###Resta

resta = A-B
print("Resta, A+B:\n", resta)

Resta, A+B:
 [[ 0  3 -3]
 [-6 -5  0]
 [-1  1  1]]


In [39]:
### Producto Matricial
producto_mat = A.dot(B)
print (producto_mat)

[[26 17  7]
 [ 1  0  5]
 [19 12  7]]


In [42]:
### Trnsposición
A_traspuesta = A.T
print("A:",A,"\n","At:",A_traspuesta)

A: [[1 3 2]
 [1 0 0]
 [1 2 2]] 
 At: [[1 1 1]
 [3 0 2]
 [2 0 2]]


In [43]:
matriz_asignaciones = [[2, 1, 0.5],
    [1, 2, 0.5],
    [2, 1, 0.5],
    [1, 0.5, 2],
    [0.5, 2, 1],
    [2, 1, 0.5],
    [0.5, 1, 2],
    [1, 2, 0.5],
    [1, 0.5, 2],
    [0.5, 1, 2]]

indice_alumnos = [
    'Rodrigo',
    'Lucia',
    'Alejandro',
    'Valeria',
    'Javier',
    'Camila',
    'Diego',
    'Gabriela',
    'Nateo',
    'Sofia'
]

In [45]:
matriz_asignaciones_np= np.array(matriz_asignaciones)
print(matriz_asignaciones_np)

[[2.  1.  0.5]
 [1.  2.  0.5]
 [2.  1.  0.5]
 [1.  0.5 2. ]
 [0.5 2.  1. ]
 [2.  1.  0.5]
 [0.5 1.  2. ]
 [1.  2.  0.5]
 [1.  0.5 2. ]
 [0.5 1.  2. ]]


In [48]:
### Creamos la matriz resta

matriz_resta=[]
for vector in matriz_asignaciones:
    new_vector = [0,0,0]
    new_vector[vector.index(2)]=0.5
    matriz_resta.append(new_vector)

matriz_resta_np = np.array(matriz_resta)

nueva_asignacion = 2*matriz_asignaciones_np-matriz_resta_np
print(nueva_asignacion)

[[3.5 2.  1. ]
 [2.  3.5 1. ]
 [3.5 2.  1. ]
 [2.  1.  3.5]
 [1.  3.5 2. ]
 [3.5 2.  1. ]
 [1.  2.  3.5]
 [2.  3.5 1. ]
 [2.  1.  3.5]
 [1.  2.  3.5]]
